<?php

namespace App\Http\Controllers;

use App\Models\Expense;
use App\Models\Vehicle;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Illuminate\View\View;

class ExpenseController extends Controller
{
    /**
     * The only expense types that may be entered manually. The other four
     * (fuel/oil/filter/maintenance) are always generated by their observers.
     */
    public const MANUAL_TYPES = [
        'spare_parts',
        'other',
    ];

    /**
     * Display a paginated listing of expenses across all vehicles.
     */
    public function index(Request $request): View
    {
        $expenses = Expense::query()
            ->with('vehicle')
            ->when($request->filled('vehicle_id'), function ($query) use ($request) {
                $query->where('vehicle_id', (int) $request->query('vehicle_id'));
            })
            ->when($request->filled('expense_type'), function ($query) use ($request) {
                $query->where('expense_type', (string) $request->query('expense_type'));
            })
            ->when($request->filled('date_from'), function ($query) use ($request) {
                $query->whereDate('expense_date', '>=', $request->query('date_from'));
            })
            ->when($request->filled('date_to'), function ($query) use ($request) {
                $query->whereDate('expense_date', '<=', $request->query('date_to'));
            })
            ->latest('expense_date');

        $totalAmount = (clone $expenses)->sum('amount');

        $expenses = $expenses->paginate(15)->withQueryString();

        return view('expenses.index', [
            'expenses' => $expenses,
            'totalAmount' => $totalAmount,
            'vehicles' => Vehicle::orderBy('internal_number')->get(),
        ]);
    }

    /**
     * Show the form for entering a new manual expense.
     */
    public function create(Request $request): View
    {
        $selectedVehicle = $request->filled('vehicle_id')
            ? Vehicle::find((int) $request->query('vehicle_id'))
            : null;

        return view('expenses.create', [
            'vehicles' => Vehicle::orderBy('internal_number')->get(),
            'selectedVehicle' => $selectedVehicle,
            'expenseTypes' => self::MANUAL_TYPES,
        ]);
    }

    /**
     * Store a newly created manual expense.
     */
    public function store(Request $request): RedirectResponse
    {
        $request->merge([
            'amount' => $request->filled('amount') ? str_replace(',', '', $request->input('amount')) : null,
        ]);

        $validated = $request->validate([
            'vehicle_id' => ['required', 'integer', 'exists:vehicles,id'],
            'expense_type' => ['required', Rule::in(self::MANUAL_TYPES)],
            'amount' => ['required', 'numeric', 'min:0'],
            'expense_date' => ['required', 'date'],
            'description' => ['nullable', 'string', 'max:255'],
        ]);

        Expense::create([
            'vehicle_id' => $validated['vehicle_id'],
            'expense_type' => $validated['expense_type'],
            'amount' => $validated['amount'],
            'expense_date' => $validated['expense_date'],
            'description' => $validated['description'] ?? null,
            'recorded_by' => $request->user()->id,
        ]);

        flash()->success('تم تسجيل المصروف بنجاح.');

        return redirect()->route('expenses.index');
    }

    /**
     * Remove the given manually-entered expense.
     */
    public function destroy(Expense $expense): RedirectResponse
    {
        if ($expense->is_auto_generated) {
            flash()->error('لا يمكن حذف مصروف تلقائي. احذف السجل المصدر (الوقود / الزيوت / الفلاتر / الصيانة) بدلاً منه.');

            return back();
        }

        $expense->delete();

        flash()->success('تم حذف المصروف بنجاح.');

        return back();
    }
}
