<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphTo;
class Expense extends Model
{
    protected $fillable = [
        'vehicle_id',
        'expense_type',
        'amount',
        'expense_date',
        'description',
        'sourceable_type',
        'sourceable_id',
        'recorded_by',
    ];

    protected $casts = [
        'amount' => 'decimal:2',
        'expense_date' => 'date',
    ];

    public function vehicle(): BelongsTo
    {
        return $this->belongsTo(Vehicle::class);
    }

    public function recordedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'recorded_by');
    }

    /** The FuelLog / VehicleOilChange / VehicleFilterChange that generated this expense, if auto-created */
    public function sourceable(): MorphTo
    {
        return $this->morphTo();
    }

    public function getIsAutoGeneratedAttribute(): bool
    {
        return $this->sourceable_type !== null;
    }
}
